# Generated by Django 4.1.2 on 2022-10-11 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_city_transaction_store_book_store_book_transaction'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='transaction',
        ),
        migrations.AddField(
            model_name='book',
            name='transaction',
            field=models.ManyToManyField(to='core.transaction'),
        ),
    ]
