# Generated by Django 4.1.2 on 2022-10-11 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_store_review'),
    ]

    operations = [
        migrations.AlterField(
            model_name='store',
            name='review',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
